config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  root 'index#index'
  resources :machines

get 'machine', to: 'machines#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    respond_to do |format|
      format.html { redirect_to :controller => 'machines', :action => 'index' }
    end
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]
  protect_from_forgery unless: -> { request.format.json? }

  # GET /machines
  # GET /machines.json
  def index
      @q = Machine.search(params[:q])
      @results = @q.result(distinct: true)
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end


  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    if @machine.deleted == true
      @machine.deleted = false
    else
      @machine.deleted = true
    end
    @machine.save
    respond_to do |format|
      format.html { redirect_to :controller => 'machines', :action => 'index', notice: 'Machine was successfully marked as deleted.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:unit_serial_number, :unit_model, :cpu_model, :unit_mfr, :ram_pass, :ram_size, :hdd_pass, :hdd_size, :hdd_serial, :order_number)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/index/index.html.erb
<h1>Grade 36</h1>
<% redirect_to :controller => 'machines', :action => 'index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grade36</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/_form.html.erb
<%= form_for(machine) do |f| %>
  <% if machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit_serial_number %>
    <%= f.text_field :unit_serial_number %>
  </div>

  <div class="field">
    <%= f.label :unit_model %>
    <%= f.text_field :unit_model %>
  </div>

  <div class="field">
    <%= f.label :cpu_model %>
    <%= f.text_field :cpu_model %>
  </div>

  <div class="field">
    <%= f.label :unit_mfr %>
    <%= f.text_field :unit_mfr %>
  </div>

  <div class="field">
    <%= f.label :ram_pass %>
    <%= f.check_box :ram_pass %>
  </div>

  <div class="field">
    <%= f.label :ram_size %>
    <%= f.number_field :ram_size %>
  </div>

  <div class="field">
    <%= f.label :hdd_pass %>
    <%= f.check_box :hdd_pass %>
  </div>

  <div class="field">
    <%= f.label :hdd_size %>
    <%= f.number_field :hdd_size %>
  </div>

  <div class="field">
    <%= f.label :hdd_serial %>
    <%= f.text_field :hdd_serial %>
  </div>
  <div class="field">
    <%= f.label :order_number %>
    <%= f.text_field :order_number %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machines/_machine.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit serial number:</strong>
  <%= machine.unit_serial_number %>
</p>

<p>
  <strong>Unit model:</strong>
  <%= machine.unit_model %>
</p>

<p>
  <strong>Cpu model:</strong>
  <%= machine.cpu_model %>
</p>

<p>
  <strong>Unit mfr:</strong>
  <%= machine.unit_mfr %>
</p>

<p>
  <strong>Ram pass:</strong>
  <%= machine.ram_pass %>
</p>

<p>
  <strong>Ram size:</strong>
  <%= machine.ram_size %>
</p>

<p>
  <strong>Hdd pass:</strong>
  <%= machine.hdd_pass %>
</p>

<p>
  <strong>Hdd size:</strong>
  <%= machine.hdd_size %>
</p>

<p>
  <strong>Hdd serial:</strong>
  <%= machine.hdd_serial %>
</p>
<p>
  <strong>Order Number:</strong>
  <%= machine.order_number %>
</p>


<%= link_to 'Edit', edit_machine_path(machine) %> |
<%= link_to 'Back', machines_path %>

app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="header-text">Machines</h1>
<div class="search-box">
    <%= search_form_for @q do |f| %>
    <div id="search-option">
        <%= f.label "Manufacturer:" %>
        <%= f.search_field :unit_mfr_eq, :placeholder => "Lenono" %>
    </div>
    <div id="search-option">
        <label>Model Number:</label>
        <%= f.search_field :unit_model_eq, :placeholder => "1738"%>
    </div>
    <div id="search-option">
        <label>HDD Size:</label>
        <%= f.select :hdd_size_eq, options_for_select(["", "80", "120"]) %>
        <span class="unit">GB</span>
    </div>
    <div id="search-option">
        <label>Serial Number:</label>
        <%= f.number_field :unit_serial_number_eq, :placeholder => "18123182312" %>
    </div>
    <div id="search-option">
        <label>Order Number:</label>
        <%= f.search_field :order_number_eq, :placeholder => "89673409" %>
    </div>
    <div id="search-option">
        <label>RAM Amount:</label>
        <%= f.number_field :ram_size_eq, :placeholder => "4" %>
        <span class="unit">GB</span>
    </div>
    <div id="search-option">
        <label>Deleted:</label>
        <input type="checkbox" name="deleted" value="true">
    </div>
    <div class="search-box-dates">
        <div id="search-option">
            <label>Before Date:</label>
            <%= f.datetime_field :created_at_lt, :value => Time.now.strftime('%Y-%m-%d') %>
        </div>
        <div id="search-option">
            <label>After Date:</label>
            <%= f.datetime_field :created_at_gt, :value => Time.now.strftime('%Y-%m-%d')%>
        </div>
    </div>
        <%= f.submit %>
    <% end %>
</div>
<table>
    <thead>
        <tr>
            <th><%= sort_link @q, :unit_serial_number, "Serial Number" %></th>
            <th><%= sort_link @q, :unit_model, "Model Number" %></th>
            <th><%= sort_link @q, :cpu_model, "CPU" %></th>
            <th><%= sort_link @q, :unit_mfr, "Manufacturer" %></th>
            <th><%= sort_link @q, :ram_size, "RAM Amount" %></th>
            <th><%= sort_link @q, :hdd_size, "HDD Size" %></th>
            <th><%= sort_link @q, :hdd_serial, "HDD Serial" %></th>
            <th><%= sort_link @q, :created_at, "Created" %></th>
            <th><%= sort_link @q, :order_number, "Order Number" %></th>
            <th><%= sort_link @q, :deleted, "Deleted" %></th>
            <th colspan="2"><a class="sort_link">Actions</a></th>
        </tr>
    </thead>

    <tbody>
        <% @results.each do |machine| %>
        <% if machine.deleted == true && params[:deleted] || !params[:deleted] && machine.deleted == false || !params[:deleted] && !machine.deleted %>
        <tr>
            <td><%= machine.unit_serial_number %></td>
            <td><%= machine.unit_model %></td>
            <td><%= machine.cpu_model %></td>
            <td><%= machine.unit_mfr %></td>
            <td><%= machine.ram_size %></td>
            <td><%= machine.hdd_size %></td>
            <td><%= machine.hdd_serial %></td>
            <td><%= machine.created_at %></td>
            <td><% if machine.order_number == 0 %>No Order Number<% else %><%= machine.order_number %><% end %></td>
            <td><% if machine.deleted == true %>Yes<% else %>No<% end %></td>
            <td><%= link_to 'View', machine, :class => "table-button" %></td>
            <td><% if machine.deleted == true %><%= link_to 'Undelete', machine, method: :delete, :class => "table-button", :id => "undelete" %><% else %>
            <%= link_to 'Mark Deleted', machine, method: :delete, data: { confirm: 'Are you sure?' }, :class => "table-button", :id => "delete" %><% end %></td>
        </tr>
        <% end %>
        <% end %>
    </tbody>
</table>

<br>

app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<h1 class="main"><%= @machine.unit_mfr %> <%= @machine.unit_model %></h1>
<p class="show">
    <strong>Serial Number:</strong>
    <%= @machine.unit_serial_number %>
</p>

<p class="show">
    <strong>CPU:</strong>
    <%= @machine.cpu_model %>
</p>

<p class="show">
    <strong>RAM Pass:</strong>
    <%= @machine.ram_pass %>
</p>

<p class="show">
    <strong>RAM Amount:</strong>
    <%= @machine.ram_size %>
</p>

<p class="show">
    <strong>Hard Drive Pass:</strong>
    <%= @machine.hdd_pass %>
</p>

<p class="show">
    <strong>Hard Drive Size:</strong>
    <%= @machine.hdd_size %>
</p>

<p class="show">
    <strong>Hard Drive Serial:</strong>
    <%= @machine.hdd_serial %>
</p>
<p class="show">
    <strong>Order Number:</strong>
    <%= @machine.order_number %>
</p>

<div class="links">
    <%= link_to 'Back', machines_path %>
</div>